###############################################
# docker-compose.yml
###############################################
version: '3'
services:
zookeeper:
image: wurstmeister/zookeeper
ports:
- "2181:2181"


kafka:
image: wurstmeister/kafka
ports:
- "9092:9092"
environment:
KAFKA_ADVERTISED_HOST_NAME: kafka
KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181


redis:
image: redis:alpine
ports:
- "6379:6379"


postgres:
image: postgres:13
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: events
ports:
- "5432:5432"


ingestion:
build: ./backend/ingestion_service
ports:
- "8000:8000"


processor:
build: ./backend/processor_service


analytics:
build: ./backend/analytics_api
ports:
- "8002:8002"


frontend:
build: ./frontend
ports:
- "3000:3000"




### Run Locally
